name: Lint
on:
  push:
    branches:
      - main
  pull_request:

concurrency: lint-${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2

      - name: Install project dependencies
        run: poetry install

      - name: Run Ruff lints
        run: poetry run ruff check ./

      - name: Run Ruff formatting
        run: poetry run ruff format --check ./

      - name: Run mypy
        run: poetry run mypy citadel
